<?php
// Add ACF Fields for Event

// Manually need to include in order to use is_plugin_active() function.
include_once( ABSPATH . 'wp-admin/includes/plugin.php' );

if ( function_exists('acf_add_local_field_group') ):

function squarecandy_events_add_fields() {
	$eventfields = array();

	$eventfields[] = array(
		'key' => 'field_8pZeHGmq7h47N',
		'label' => 'Pre-event',
		'name' => 'pre_event_tab',
		'type' => 'tab',
	);

	$eventfields[] = array(
		'key' => 'field_0aFVqq90AQvk0',
		'label' => 'Event Image',
		'name' => 'featured_image',
		'type' => 'image',
		'return_format' => 'id',
		'preview_size' => 'medium',

 	);

	$eventfields[] = array(
		'key' => 'field_5616bbe39fbec',
		'label' => '(Start) Date',
		'name' => 'start_date',
		'type' => 'date_picker',
		'required' => 1,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '40',
		),
		'display_format' => 'F j, Y',
		'return_format' => 'F j, Y',
		'first_day' => 0,
	);
	$eventfields[] = array(
		'key' => 'field_5616bcdfb642d',
		'label' => 'All Day',
		'name' => 'all_day',
		'type' => 'true_false',
		'wrapper' => array(
			'width' => 10,
		),
		'default_value' => 0,
	);
	$eventfields[] = array(
		'key' => 'field_5616bd4ca2b0f',
		'label' => 'Show End Date/Time',
		'name' => 'multi_day',
		'type' => 'true_false',
		'wrapper' => array(
			'width' => '20',
		),
		'default_value' => 0,
	);
	$eventfields[] = array(
		'key' => 'field_5616bc2b9fbed',
		'label' => '(Start) Time',
		'name' => 'start_time',
		'type' => 'time_picker',
		'required' => 1,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_5616bcdfb642d',
					'operator' => '!=',
					'value' => '1',
				),
			),
		),
		'wrapper' => array(
			'width' => '30',
		),
		'display_format' => 'g:i a',
		'return_format' => 'g:i a',
	);
	$eventfields[] = array(
		'key' => 'field_5616bd75112ca',
		'label' => 'End Date',
		'name' => 'end_date',
		'type' => 'date_picker',
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_5616bd4ca2b0f',
					'operator' => '==',
					'value' => '1',
				),
			),
		),
		'wrapper' => array(
			'width' => '70',
		),
		'display_format' => 'F j, Y',
		'return_format' => 'F j, Y',
		'first_day' => 0,
	);
	$eventfields[] = array(
		'key' => 'field_5616bd8e112cb',
		'label' => 'End Time',
		'name' => 'end_time',
		'type' => 'time_picker',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_5616bcdfb642d',
					'operator' => '!=',
					'value' => '1',
				),
				array(
					'field' => 'field_5616bd4ca2b0f',
					'operator' => '==',
					'value' => '1',
				),
			),
		),
		'wrapper' => array(
			'width' => '30',
		),
		'display_format' => 'g:i a',
		'return_format' => 'g:i a',
	);

	$eventfields[] = array(
		'key' => 'field_l21uM3MZS6gtc',
		'label' => 'Event Currency',
		'name' => 'event_currency',
		'type' => 'select',
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => 25,
		),
		'return_format' => 'array',
		'choices' => array(
			// 'AED' => '&#x62f;.&#x625;',
			// 'AFN' => '&#x60b;',
			// 'ALL' => 'L',
			// 'AMD' => 'AMD',
			// 'ANG' => '&fnof;',
			// 'AOA' => 'Kz',
			// 'ARS' => '&#36;',
			'AUD' => '&#36;',
			// 'AWG' => '&fnof;',
			// 'AZN' => 'AZN',
			// 'BAM' => 'KM',
			// 'BBD' => '&#36;',
			// 'BDT' => '&#2547;&nbsp;',
			// 'BGN' => '&#1083;&#1074;.',
			// 'BHD' => '.&#x62f;.&#x628;',
			// 'BIF' => 'Fr',
			// 'BMD' => '&#36;',
			// 'BND' => '&#36;',
			// 'BOB' => 'Bs.',
			// 'BRL' => '&#82;&#36;',
			// 'BSD' => '&#36;',
			// 'BTC' => '&#3647;',
			// 'BTN' => 'Nu.',
			// 'BWP' => 'P',
			// 'BYR' => 'Br',
			// 'BZD' => '&#36;',
			// 'CAD' => '&#36;',
			// 'CDF' => 'Fr',
			// 'CHF' => '&#67;&#72;&#70;',
			// 'CLP' => '&#36;',
			// 'CNY' => '&yen;',
			// 'COP' => '&#36;',
			'CRC' => '&#x20a1;',
			// 'CUC' => '&#36;',
			// 'CUP' => '&#36;',
			// 'CVE' => '&#36;',
			// 'CZK' => '&#75;&#269;',
			// 'DJF' => 'Fr',
			// 'DKK' => 'DKK',
			// 'DOP' => 'RD&#36;',
			// 'DZD' => '&#x62f;.&#x62c;',
			// 'EGP' => 'EGP',
			// 'ERN' => 'Nfk',
			// 'ETB' => 'Br',
			'EUR' => '&euro;',
			// 'FJD' => '&#36;',
			// 'FKP' => '&pound;',
			'GBP' => '&pound;',
			// 'GEL' => '&#x10da;',
			// 'GGP' => '&pound;',
			// 'GHS' => '&#x20b5;',
			// 'GIP' => '&pound;',
			// 'GMD' => 'D',
			// 'GNF' => 'Fr',
			// 'GTQ' => 'Q',
			// 'GYD' => '&#36;',
			// 'HKD' => '&#36;',
			// 'HNL' => 'L',
			// 'HRK' => 'Kn',
			// 'HTG' => 'G',
			// 'HUF' => '&#70;&#116;',
			// 'IDR' => 'Rp',
			// 'ILS' => '&#8362;',
			// 'IMP' => '&pound;',
			// 'INR' => '&#8377;',
			// 'IQD' => '&#x639;.&#x62f;',
			// 'IRR' => '&#xfdfc;',
			// 'ISK' => 'Kr.',
			// 'JEP' => '&pound;',
			// 'JMD' => '&#36;',
			// 'JOD' => '&#x62f;.&#x627;',
			// 'JPY' => '&yen;',
			// 'KES' => 'KSh',
			// 'KGS' => '&#x43b;&#x432;',
			// 'KHR' => '&#x17db;',
			// 'KMF' => 'Fr',
			// 'KPW' => '&#x20a9;',
			// 'KRW' => '&#8361;',
			// 'KWD' => '&#x62f;.&#x643;',
			// 'KYD' => '&#36;',
			// 'KZT' => 'KZT',
			// 'LAK' => '&#8365;',
			// 'LBP' => '&#x644;.&#x644;',
			// 'LKR' => '&#xdbb;&#xdd4;',
			// 'LRD' => '&#36;',
			// 'LSL' => 'L',
			// 'LYD' => '&#x644;.&#x62f;',
			// 'MAD' => '&#x62f;. &#x645;.',
			// 'MAD' => '&#x62f;.&#x645;.',
			// 'MDL' => 'L',
			// 'MGA' => 'Ar',
			// 'MKD' => '&#x434;&#x435;&#x43d;',
			// 'MMK' => 'Ks',
			// 'MNT' => '&#x20ae;',
			// 'MOP' => 'P',
			// 'MRO' => 'UM',
			// 'MUR' => '&#x20a8;',
			// 'MVR' => '.&#x783;',
			// 'MWK' => 'MK',
			// 'MXN' => '&#36;',
			// 'MYR' => '&#82;&#77;',
			// 'MZN' => 'MT',
			// 'NAD' => '&#36;',
			// 'NGN' => '&#8358;',
			// 'NIO' => 'C&#36;',
			// 'NOK' => '&#107;&#114;',
			// 'NPR' => '&#8360;',
			// 'NZD' => '&#36;',
			// 'OMR' => '&#x631;.&#x639;.',
			// 'PAB' => 'B/.',
			// 'PEN' => 'S/.',
			// 'PGK' => 'K',
			// 'PHP' => '&#8369;',
			// 'PKR' => '&#8360;',
			// 'PLN' => '&#122;&#322;',
			// 'PRB' => '&#x440;.',
			// 'PYG' => '&#8370;',
			// 'QAR' => '&#x631;.&#x642;',
			// 'RMB' => '&yen;',
			// 'RON' => 'lei',
			// 'RSD' => '&#x434;&#x438;&#x43d;.',
			// 'RUB' => '&#8381;',
			// 'RWF' => 'Fr',
			// 'SAR' => '&#x631;.&#x633;',
			// 'SBD' => '&#36;',
			// 'SCR' => '&#x20a8;',
			// 'SDG' => '&#x62c;.&#x633;.',
			// 'SEK' => '&#107;&#114;',
			// 'SGD' => '&#36;',
			// 'SHP' => '&pound;',
			// 'SLL' => 'Le',
			// 'SOS' => 'Sh',
			// 'SRD' => '&#36;',
			// 'SSP' => '&pound;',
			// 'STD' => 'Db',
			// 'SYP' => '&#x644;.&#x633;',
			// 'SZL' => 'L',
			// 'THB' => '&#3647;',
			// 'TJS' => '&#x405;&#x41c;',
			// 'TMT' => 'm',
			// 'TND' => '&#x62f;.&#x62a;',
			// 'TOP' => 'T&#36;',
			// 'TRY' => '&#8378;',
			// 'TTD' => '&#36;',
			// 'TWD' => '&#78;&#84;&#36;',
			// 'TZS' => 'Sh',
			// 'UAH' => '&#8372;',
			// 'UGX' => 'UGX',
			// 'USD' => '&#36;',
			// 'UYU' => '&#36;',
			// 'UZS' => 'UZS',
			// 'VEF' => 'Bs F',
			// 'VND' => '&#8363;',
			// 'VUV' => 'Vt',
			// 'WST' => 'T',
			// 'XAF' => 'Fr',
			// 'XCD' => '&#36;',
			// 'XOF' => 'Fr',
			// 'XPF' => 'Fr',
			// 'YER' => '&#xfdfc;',
			// 'ZAR' => '&#82;',
			// 'ZMW' => 'ZK',
		),
		'default_value' => 'AUD',
	);

	$eventfields[] = array(
		'key' => 'field_A3awg38hVMO0G',
		'label' => 'Event Price',
		'name' => 'event_price',
		'type' => 'radio',
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => 25,
		),
		'choices' => array(
			'free' => 'Free',
		),
		'default_value' => 'free',
		'other_choice' => true,
		'layout' => 'horizontal',
	);

	$eventfields[] = array(
		'key' => 'field_5616bedeed0a9',
		'label' => 'Venue Name',
		'name' => 'venue',
		'type' => 'text',
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => 25,
		),
	);
	$eventfields[] = array(
		'key' => 'field_5616beefed0aa',
		'label' => 'Venue Link',
		'name' => 'venue_link',
		'type' => 'url',
		'wrapper' => array(
			'width' => 25,
		),
	);
	$eventfields[] = array(
		'key' => 'field_address226474957',
		'label' => 'Address',
		'name' => 'address',
		'type' => 'text',
	);
	$eventfields[] = array(
		'key' => 'field_city585d8171a157e',
		'label' => 'City',
		'name' => 'city',
		'type' => 'text',
		'wrapper' => array(
			'width' => 25,
		),
	);
	$eventfields[] = array(
		'key' => 'field_state94823hf873',
		'label' => 'State/Province',
		'name' => 'state',
		'type' => 'text',
		'wrapper' => array(
			'width' => 25,
		),
	);
	$eventfields[] = array(
		'key' => 'field_zipfj8392y38r9',
		'label' => 'Postal Code',
		'name' => 'zip',
		'type' => 'text',
		'wrapper' => array(
			'width' => 25,
		),
	);
	$eventfields[] = array(
		'key' => 'field_country1749283947',
		'label' => 'Country',
		'name' => 'country',
		'type' => 'select',
		'wrapper' => array(
			'width' => 25,
		),
		'choices' => array(
			'AF' => __( 'Afghanistan', 'squarecandy' ),
			'AX' => __( '&#197;land Islands', 'squarecandy' ),
			'AL' => __( 'Albania', 'squarecandy' ),
			'DZ' => __( 'Algeria', 'squarecandy' ),
			'AS' => __( 'American Samoa', 'squarecandy' ),
			'AD' => __( 'Andorra', 'squarecandy' ),
			'AO' => __( 'Angola', 'squarecandy' ),
			'AI' => __( 'Anguilla', 'squarecandy' ),
			'AQ' => __( 'Antarctica', 'squarecandy' ),
			'AG' => __( 'Antigua and Barbuda', 'squarecandy' ),
			'AR' => __( 'Argentina', 'squarecandy' ),
			'AM' => __( 'Armenia', 'squarecandy' ),
			'AW' => __( 'Aruba', 'squarecandy' ),
			'AU' => __( 'Australia', 'squarecandy' ),
			'AT' => __( 'Austria', 'squarecandy' ),
			'AZ' => __( 'Azerbaijan', 'squarecandy' ),
			'BS' => __( 'Bahamas', 'squarecandy' ),
			'BH' => __( 'Bahrain', 'squarecandy' ),
			'BD' => __( 'Bangladesh', 'squarecandy' ),
			'BB' => __( 'Barbados', 'squarecandy' ),
			'BY' => __( 'Belarus', 'squarecandy' ),
			'BE' => __( 'Belgium', 'squarecandy' ),
			'PW' => __( 'Belau', 'squarecandy' ),
			'BZ' => __( 'Belize', 'squarecandy' ),
			'BJ' => __( 'Benin', 'squarecandy' ),
			'BM' => __( 'Bermuda', 'squarecandy' ),
			'BT' => __( 'Bhutan', 'squarecandy' ),
			'BO' => __( 'Bolivia', 'squarecandy' ),
			'BQ' => __( 'Bonaire, Saint Eustatius and Saba', 'squarecandy' ),
			'BA' => __( 'Bosnia and Herzegovina', 'squarecandy' ),
			'BW' => __( 'Botswana', 'squarecandy' ),
			'BV' => __( 'Bouvet Island', 'squarecandy' ),
			'BR' => __( 'Brazil', 'squarecandy' ),
			'IO' => __( 'British Indian Ocean Territory', 'squarecandy' ),
			'VG' => __( 'British Virgin Islands', 'squarecandy' ),
			'BN' => __( 'Brunei', 'squarecandy' ),
			'BG' => __( 'Bulgaria', 'squarecandy' ),
			'BF' => __( 'Burkina Faso', 'squarecandy' ),
			'BI' => __( 'Burundi', 'squarecandy' ),
			'KH' => __( 'Cambodia', 'squarecandy' ),
			'CM' => __( 'Cameroon', 'squarecandy' ),
			'CA' => __( 'Canada', 'squarecandy' ),
			'CV' => __( 'Cape Verde', 'squarecandy' ),
			'KY' => __( 'Cayman Islands', 'squarecandy' ),
			'CF' => __( 'Central African Republic', 'squarecandy' ),
			'TD' => __( 'Chad', 'squarecandy' ),
			'CL' => __( 'Chile', 'squarecandy' ),
			'CN' => __( 'China', 'squarecandy' ),
			'CX' => __( 'Christmas Island', 'squarecandy' ),
			'CC' => __( 'Cocos (Keeling) Islands', 'squarecandy' ),
			'CO' => __( 'Colombia', 'squarecandy' ),
			'KM' => __( 'Comoros', 'squarecandy' ),
			'CG' => __( 'Congo (Brazzaville)', 'squarecandy' ),
			'CD' => __( 'Congo (Kinshasa)', 'squarecandy' ),
			'CK' => __( 'Cook Islands', 'squarecandy' ),
			'CR' => __( 'Costa Rica', 'squarecandy' ),
			'HR' => __( 'Croatia', 'squarecandy' ),
			'CU' => __( 'Cuba', 'squarecandy' ),
			'CW' => __( 'Cura&ccedil;ao', 'squarecandy' ),
			'CY' => __( 'Cyprus', 'squarecandy' ),
			'CZ' => __( 'Czech Republic', 'squarecandy' ),
			'DK' => __( 'Denmark', 'squarecandy' ),
			'DJ' => __( 'Djibouti', 'squarecandy' ),
			'DM' => __( 'Dominica', 'squarecandy' ),
			'DO' => __( 'Dominican Republic', 'squarecandy' ),
			'EC' => __( 'Ecuador', 'squarecandy' ),
			'EG' => __( 'Egypt', 'squarecandy' ),
			'SV' => __( 'El Salvador', 'squarecandy' ),
			'GQ' => __( 'Equatorial Guinea', 'squarecandy' ),
			'ER' => __( 'Eritrea', 'squarecandy' ),
			'EE' => __( 'Estonia', 'squarecandy' ),
			'ET' => __( 'Ethiopia', 'squarecandy' ),
			'FK' => __( 'Falkland Islands', 'squarecandy' ),
			'FO' => __( 'Faroe Islands', 'squarecandy' ),
			'FJ' => __( 'Fiji', 'squarecandy' ),
			'FI' => __( 'Finland', 'squarecandy' ),
			'FR' => __( 'France', 'squarecandy' ),
			'GF' => __( 'French Guiana', 'squarecandy' ),
			'PF' => __( 'French Polynesia', 'squarecandy' ),
			'TF' => __( 'French Southern Territories', 'squarecandy' ),
			'GA' => __( 'Gabon', 'squarecandy' ),
			'GM' => __( 'Gambia', 'squarecandy' ),
			'GE' => __( 'Georgia', 'squarecandy' ),
			'DE' => __( 'Germany', 'squarecandy' ),
			'GH' => __( 'Ghana', 'squarecandy' ),
			'GI' => __( 'Gibraltar', 'squarecandy' ),
			'GR' => __( 'Greece', 'squarecandy' ),
			'GL' => __( 'Greenland', 'squarecandy' ),
			'GD' => __( 'Grenada', 'squarecandy' ),
			'GP' => __( 'Guadeloupe', 'squarecandy' ),
			'GU' => __( 'Guam', 'squarecandy' ),
			'GT' => __( 'Guatemala', 'squarecandy' ),
			'GG' => __( 'Guernsey', 'squarecandy' ),
			'GN' => __( 'Guinea', 'squarecandy' ),
			'GW' => __( 'Guinea-Bissau', 'squarecandy' ),
			'GY' => __( 'Guyana', 'squarecandy' ),
			'HT' => __( 'Haiti', 'squarecandy' ),
			'HM' => __( 'Heard Island and McDonald Islands', 'squarecandy' ),
			'HN' => __( 'Honduras', 'squarecandy' ),
			'HK' => __( 'Hong Kong', 'squarecandy' ),
			'HU' => __( 'Hungary', 'squarecandy' ),
			'IS' => __( 'Iceland', 'squarecandy' ),
			'IN' => __( 'India', 'squarecandy' ),
			'ID' => __( 'Indonesia', 'squarecandy' ),
			'IR' => __( 'Iran', 'squarecandy' ),
			'IQ' => __( 'Iraq', 'squarecandy' ),
			'IE' => __( 'Ireland', 'squarecandy' ),
			'IM' => __( 'Isle of Man', 'squarecandy' ),
			'IL' => __( 'Israel', 'squarecandy' ),
			'IT' => __( 'Italy', 'squarecandy' ),
			'CI' => __( 'Ivory Coast', 'squarecandy' ),
			'JM' => __( 'Jamaica', 'squarecandy' ),
			'JP' => __( 'Japan', 'squarecandy' ),
			'JE' => __( 'Jersey', 'squarecandy' ),
			'JO' => __( 'Jordan', 'squarecandy' ),
			'KZ' => __( 'Kazakhstan', 'squarecandy' ),
			'KE' => __( 'Kenya', 'squarecandy' ),
			'KI' => __( 'Kiribati', 'squarecandy' ),
			'KW' => __( 'Kuwait', 'squarecandy' ),
			'KG' => __( 'Kyrgyzstan', 'squarecandy' ),
			'LA' => __( 'Laos', 'squarecandy' ),
			'LV' => __( 'Latvia', 'squarecandy' ),
			'LB' => __( 'Lebanon', 'squarecandy' ),
			'LS' => __( 'Lesotho', 'squarecandy' ),
			'LR' => __( 'Liberia', 'squarecandy' ),
			'LY' => __( 'Libya', 'squarecandy' ),
			'LI' => __( 'Liechtenstein', 'squarecandy' ),
			'LT' => __( 'Lithuania', 'squarecandy' ),
			'LU' => __( 'Luxembourg', 'squarecandy' ),
			'MO' => __( 'Macao S.A.R., China', 'squarecandy' ),
			'MK' => __( 'Macedonia', 'squarecandy' ),
			'MG' => __( 'Madagascar', 'squarecandy' ),
			'MW' => __( 'Malawi', 'squarecandy' ),
			'MY' => __( 'Malaysia', 'squarecandy' ),
			'MV' => __( 'Maldives', 'squarecandy' ),
			'ML' => __( 'Mali', 'squarecandy' ),
			'MT' => __( 'Malta', 'squarecandy' ),
			'MH' => __( 'Marshall Islands', 'squarecandy' ),
			'MQ' => __( 'Martinique', 'squarecandy' ),
			'MR' => __( 'Mauritania', 'squarecandy' ),
			'MU' => __( 'Mauritius', 'squarecandy' ),
			'YT' => __( 'Mayotte', 'squarecandy' ),
			'MX' => __( 'Mexico', 'squarecandy' ),
			'FM' => __( 'Micronesia', 'squarecandy' ),
			'MD' => __( 'Moldova', 'squarecandy' ),
			'MC' => __( 'Monaco', 'squarecandy' ),
			'MN' => __( 'Mongolia', 'squarecandy' ),
			'ME' => __( 'Montenegro', 'squarecandy' ),
			'MS' => __( 'Montserrat', 'squarecandy' ),
			'MA' => __( 'Morocco', 'squarecandy' ),
			'MZ' => __( 'Mozambique', 'squarecandy' ),
			'MM' => __( 'Myanmar', 'squarecandy' ),
			'NA' => __( 'Namibia', 'squarecandy' ),
			'NR' => __( 'Nauru', 'squarecandy' ),
			'NP' => __( 'Nepal', 'squarecandy' ),
			'NL' => __( 'Netherlands', 'squarecandy' ),
			'NC' => __( 'New Caledonia', 'squarecandy' ),
			'NZ' => __( 'New Zealand', 'squarecandy' ),
			'NI' => __( 'Nicaragua', 'squarecandy' ),
			'NE' => __( 'Niger', 'squarecandy' ),
			'NG' => __( 'Nigeria', 'squarecandy' ),
			'NU' => __( 'Niue', 'squarecandy' ),
			'NF' => __( 'Norfolk Island', 'squarecandy' ),
			'MP' => __( 'Northern Mariana Islands', 'squarecandy' ),
			'KP' => __( 'North Korea', 'squarecandy' ),
			'NO' => __( 'Norway', 'squarecandy' ),
			'OM' => __( 'Oman', 'squarecandy' ),
			'PK' => __( 'Pakistan', 'squarecandy' ),
			'PS' => __( 'Palestinian Territory', 'squarecandy' ),
			'PA' => __( 'Panama', 'squarecandy' ),
			'PG' => __( 'Papua New Guinea', 'squarecandy' ),
			'PY' => __( 'Paraguay', 'squarecandy' ),
			'PE' => __( 'Peru', 'squarecandy' ),
			'PH' => __( 'Philippines', 'squarecandy' ),
			'PN' => __( 'Pitcairn', 'squarecandy' ),
			'PL' => __( 'Poland', 'squarecandy' ),
			'PT' => __( 'Portugal', 'squarecandy' ),
			'PR' => __( 'Puerto Rico', 'squarecandy' ),
			'QA' => __( 'Qatar', 'squarecandy' ),
			'RE' => __( 'Reunion', 'squarecandy' ),
			'RO' => __( 'Romania', 'squarecandy' ),
			'RU' => __( 'Russia', 'squarecandy' ),
			'RW' => __( 'Rwanda', 'squarecandy' ),
			'BL' => __( 'Saint Barth&eacute;lemy', 'squarecandy' ),
			'SH' => __( 'Saint Helena', 'squarecandy' ),
			'KN' => __( 'Saint Kitts and Nevis', 'squarecandy' ),
			'LC' => __( 'Saint Lucia', 'squarecandy' ),
			'MF' => __( 'Saint Martin (French part)', 'squarecandy' ),
			'SX' => __( 'Saint Martin (Dutch part)', 'squarecandy' ),
			'PM' => __( 'Saint Pierre and Miquelon', 'squarecandy' ),
			'VC' => __( 'Saint Vincent and the Grenadines', 'squarecandy' ),
			'SM' => __( 'San Marino', 'squarecandy' ),
			'ST' => __( 'S&atilde;o Tom&eacute; and Pr&iacute;ncipe', 'squarecandy' ),
			'SA' => __( 'Saudi Arabia', 'squarecandy' ),
			'SN' => __( 'Senegal', 'squarecandy' ),
			'RS' => __( 'Serbia', 'squarecandy' ),
			'SC' => __( 'Seychelles', 'squarecandy' ),
			'SL' => __( 'Sierra Leone', 'squarecandy' ),
			'SG' => __( 'Singapore', 'squarecandy' ),
			'SK' => __( 'Slovakia', 'squarecandy' ),
			'SI' => __( 'Slovenia', 'squarecandy' ),
			'SB' => __( 'Solomon Islands', 'squarecandy' ),
			'SO' => __( 'Somalia', 'squarecandy' ),
			'ZA' => __( 'South Africa', 'squarecandy' ),
			'GS' => __( 'South Georgia/Sandwich Islands', 'squarecandy' ),
			'KR' => __( 'South Korea', 'squarecandy' ),
			'SS' => __( 'South Sudan', 'squarecandy' ),
			'ES' => __( 'Spain', 'squarecandy' ),
			'LK' => __( 'Sri Lanka', 'squarecandy' ),
			'SD' => __( 'Sudan', 'squarecandy' ),
			'SR' => __( 'Suriname', 'squarecandy' ),
			'SJ' => __( 'Svalbard and Jan Mayen', 'squarecandy' ),
			'SZ' => __( 'Swaziland', 'squarecandy' ),
			'SE' => __( 'Sweden', 'squarecandy' ),
			'CH' => __( 'Switzerland', 'squarecandy' ),
			'SY' => __( 'Syria', 'squarecandy' ),
			'TW' => __( 'Taiwan', 'squarecandy' ),
			'TJ' => __( 'Tajikistan', 'squarecandy' ),
			'TZ' => __( 'Tanzania', 'squarecandy' ),
			'TH' => __( 'Thailand', 'squarecandy' ),
			'TL' => __( 'Timor-Leste', 'squarecandy' ),
			'TG' => __( 'Togo', 'squarecandy' ),
			'TK' => __( 'Tokelau', 'squarecandy' ),
			'TO' => __( 'Tonga', 'squarecandy' ),
			'TT' => __( 'Trinidad and Tobago', 'squarecandy' ),
			'TN' => __( 'Tunisia', 'squarecandy' ),
			'TR' => __( 'Turkey', 'squarecandy' ),
			'TM' => __( 'Turkmenistan', 'squarecandy' ),
			'TC' => __( 'Turks and Caicos Islands', 'squarecandy' ),
			'TV' => __( 'Tuvalu', 'squarecandy' ),
			'UG' => __( 'Uganda', 'squarecandy' ),
			'UA' => __( 'Ukraine', 'squarecandy' ),
			'AE' => __( 'United Arab Emirates', 'squarecandy' ),
			'GB' => __( 'United Kingdom (UK)', 'squarecandy' ),
			'US' => __( 'United States (US)', 'squarecandy' ),
			'UM' => __( 'United States (US) Minor Outlying Islands', 'squarecandy' ),
			'VI' => __( 'United States (US) Virgin Islands', 'squarecandy' ),
			'UY' => __( 'Uruguay', 'squarecandy' ),
			'UZ' => __( 'Uzbekistan', 'squarecandy' ),
			'VU' => __( 'Vanuatu', 'squarecandy' ),
			'VA' => __( 'Vatican', 'squarecandy' ),
			'VE' => __( 'Venezuela', 'squarecandy' ),
			'VN' => __( 'Vietnam', 'squarecandy' ),
			'WF' => __( 'Wallis and Futuna', 'squarecandy' ),
			'EH' => __( 'Western Sahara', 'squarecandy' ),
			'WS' => __( 'Samoa', 'squarecandy' ),
			'YE' => __( 'Yemen', 'squarecandy' ),
			'ZM' => __( 'Zambia', 'squarecandy' ),
			'ZW' => __( 'Zimbabwe', 'squarecandy' ),
		),
		// TODO: Figure out why this is not being set as default value.
		'default_value' => 'AU',
	);

	$instructions = '';
	if ( !get_field('google_maps_api_key','option') ) {
		$instructions = 'Looks like you don‘t have a Google Maps API key yet. First,
			<a href="https://developers.google.com/maps/documentation/javascript/get-api-key"
			target="_blank">get your API key here</a>. Then enter it on the
			<a href="/wp-admin/edit.php?post_type=event&page=acf-options-event-settings">Events
			Settings page here</a>.';
	}

	$default_zoom = get_field('default_zoom_level', 'option') ? get_field('default_zoom_level', 'option') : 15;
	$eventfields[] = array(
		'key' => 'field_5616c0e68be8f',
		'label' => 'Venue Location',
		'name' => 'venue_location',
		'type' => 'google_map',
		'instructions' => $instructions,
		'center_lat' => '40.6976701',
		'center_lng' => '-74.25987,10',
		'zoom' => $default_zoom,
		'height' => '280',
	);
	$eventfields[] = array(
		'key' => 'field_mapzoom273489241f6',
		'label' => 'Map Zoom Level',
		'name' => 'zoom_level',
		'type' => 'range',
		'instructions' => 'select how far zoomed in this map appears (setting reflected on front-end event page only, not in the map box above)',
		'default_value' => $default_zoom,
		'min' => 8,
		'max' => 21,
		'step' => 1,
		'prepend' => '-',
		'append' => '+',
	);
	$eventfields[] = array(
		'key' => 'field_5616befced0ab',
		'label' => 'More Info Link',
		'name' => 'more_info_link',
		'type' => 'url',
		'wrapper' => array(
			'width' => 50,
		),
		'instructions' => __( 'The link to where people can go to obtain more information about the event.', 'squarecandy' ),
	);
	$eventfields[] = array(
		'key' => 'field_5616bf58ed0ac',
		'label' => 'Registration Link',
		'name' => 'registration_link',
		'type' => 'url',
		'wrapper' => array(
			'width' => 50,
		),

		'instructions' => __( 'The link to the event to where people have to register for free or for a fee.', 'squarecandy' ),
	);
	$eventfields[] = array(
		'key' => 'field_facebooklink7293484',
		'label' => 'Facebook Event Link',
		'name' => 'facebook_link',
		'type' => 'url',
	);

	$eventfields[] = array(
		'key' => 'field_v94KRcmsS57Oc',
		'label' => 'Event Material',
		'name' => 'event_material',
		'type' => 'repeater',
		'instructions' => 'Upload any relevant material to the event.',
		'collapsed'         => '0',
		'min'               => '',
		'max'               => '',
		'layout'            => 'table',
		'button_label'      => 'Add event material',
		'sub_fields' => array(
			// Add Event Material Sub Fields to Event Material Repeater.
			array(
				'key' => 'field_jQ5h2ukY1e0gx',
				'label' => 'Event Material File',
				'name' => 'event_material_file',
				'type' => 'file',
				'parent' => 'event_material',
			),
		),
	);

	$eventfields[] = array(
		'key' => 'field_5616bf8eed0ad',
		'label' => 'Short Description',
		'name' => 'short_description',
		'type' => 'wysiwyg',
		'instructions' => 'A short text description for the event. Limit 210 characters.  You may repeat this text and elaborate further in the main body field below.',
		'wrapper' => array(
			'width' => '',
			'class' => 'short_wysiwyg',
			'id' => '',
		),
		'tabs' => 'all',
		'toolbar' => 'basic',
		'media_upload' => 0,
		'default_value' => '',
		'delay' => 0,
	);

	$eventfields[] = array(
		'key' => 'field_306iMBT3zZMHu',
		'label' => 'Post-event',
		'name' => 'post_event_tab',
		'type' => 'tab',
	);

	$eventfields[] = array(
		'key' => 'field_EO4v6Xoaz30BM',
		'label' => 'Event Summary',
		'name' => 'event_summary',
		'type' => 'wysiwyg',
		'instructions' => 'A short event summary for the event. Limit 210 characters.',
		'wrapper' => array(
			'width' => '',
			'class' => 'short_wysiwyg',
			'id' => '',
		),
		'tabs' => 'all',
		'toolbar' => 'basic',
		'media_upload' => 0,
		'default_value' => '',
		'delay' => 0,
	);

	$eventfields[] = array(
		'key' => 'field_zGhmOM5t7a7g0',
		'label' => 'Event Gallery',
		'name' => 'event_gallery',
		'type' => 'gallery',
		'instructions' => 'Upload images pertinent to the event',
	);

	// if ( get_field('enable_categories', 'option') ) :

		// $eventfields[] = array(
		// 	'key' => 'field_5b9318c9d74e7',
		// 	'label' => 'Category',
		// 	'name' => 'category',
		// 	'type' => 'taxonomy',
		// 	'taxonomy' => 'events-category',
		// 	'field_type' => 'checkbox',
		// 	'add_term' => 1,
		// 	'save_terms' => 1,
		// 	'load_terms' => 1,
		// 	'return_format' => 'object',
		// 	'multiple' => 1,
		// 	'allow_null' => 1,
		// );

		// function remove_default_event_category_metabox() {
		// 	remove_meta_box( 'tagsdiv-events-category', 'event', 'side' );
		// }
		// add_action( 'admin_menu' , 'remove_default_event_category_metabox' );

	// endif;

	// allow linking to "works" if the Square Candy ACF Composer Works plugin is enabled
	if ( is_plugin_active('squarecandy-acf-works/squarecandy-acf-works.php') ) :
		$eventfields[] = array(
			'key' => 'field_5841cdf6350d1',
			'label' => 'Featured Works',
			'name' => 'featured_works',
			'type' => 'relationship',
			'post_type' => array(
				0 => 'works',
			),
			'filters' => array(
				0 => 'search',
			),
			'return_format' => 'object',
		);
	endif;

	acf_add_local_field_group(array(
		'key' => 'group_5616bbdb43b9f',
		'title' => 'Event Fields',
		'fields' => $eventfields,
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'event',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
			0 => 'excerpt',
			1 => 'custom_fields',
			2 => 'discussion',
			3 => 'comments',
			4 => 'format',
			5 => 'page_attributes',
			// 6 => 'categories',
			7 => 'tags',
			8 => 'send-trackbacks',
		),
		'active' => 1,
		'description' => '',
	));




}
add_action( 'after_setup_theme', 'squarecandy_events_add_fields' );


$date_formats = array(
	'l, F j, Y' => 'Saturday, October 26, 1985',
	'F j, Y' => 'October 26, 1985',
	'l, F j' => 'Saturday, October 26',
	'F j' => 'October 26',
	'D, M j, Y' => 'Sat, Oct 26, 1985',
	'M j, Y' => 'Oct 26, 1985',
	'D, M j' => 'Sat, Oct 26',
	'M j' => 'Oct 26',
	'm/d/Y' => '10/26/1985',
	'm/d' => '10/26',
	'Y-m-d' => '1985-10-26',
	'l, j F, Y' => 'Saturday, 26 October, 1985',
	'j F, Y' => '26 October, 1985',
	'l, j F' => 'Saturday, 26 October',
	'j F' => '26 October',
	'D, j M, Y' => 'Sat, 26 Oct, 1985',
	'j M, Y' => '26 Oct, 1985',
	'D, j M' => 'Sat, 26 Oct',
	'j M' => '26 Oct',
	'd/m/Y' => '26/10/1985',
	'd/m' => '26/10',
);

acf_add_local_field_group(array(
	'key' => 'group_5a6e81f786514',
	'title' => 'Event Options',
	'fields' => array(
		array(
			'key' => 'field_5a71126cf1def',
			'label' => 'Date Formats',
			'name' => 'date_formats',
			'type' => 'group',
			'instructions' => 'Choose the date formats you want to use throughout the events system.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5a71125ff1dee',
					'label' => 'Main Date Format',
					'name' => 'date_format',
					'type' => 'select',
					'choices' => $date_formats,
					'default_value' => array(
						0 => 'l, F j, Y',
					),
					'allow_null' => 0,
					'return_format' => 'value',
					'wrapper' => array(
						'width' => '33',
					),
				),
				array(
					'key' => 'field_5a7119ab98e68',
					'label' => 'Multi-Day Start Date',
					'name' => 'date_format_multi_start',
					'type' => 'select',
					'choices' => $date_formats,
					'default_value' => array(
						0 => 'F j',
					),
					'allow_null' => 0,
					'return_format' => 'value',
					'wrapper' => array(
						'width' => '33',
					),
				),
				array(
					'key' => 'field_5a7119af98e69',
					'label' => 'Multi-Day End Date',
					'name' => 'date_format_multi_end',
					'type' => 'select',
					'choices' => $date_formats,
					'default_value' => array(
						0 => 'F j, Y',
					),
					'allow_null' => 0,
					'return_format' => 'value',
					'wrapper' => array(
						'width' => '33',
					),
				),
				array(
					'key' => 'field_5a7119b198e6a',
					'label' => 'Compact Date Format',
					'name' => 'date_format_compact',
					'type' => 'select',
					'choices' => $date_formats,
					'default_value' => array(
						0 => 'D, M j',
					),
					'allow_null' => 0,
					'return_format' => 'value',
					'wrapper' => array(
						'width' => '33',
					),
				),
				array(
					'key' => 'field_5a711a6b98e6b',
					'label' => 'Compact Multi-Day Start Date',
					'name' => 'date_format_compact_multi_start',
					'type' => 'select',
					'choices' => $date_formats,
					'default_value' => array(
						0 => 'M j',
					),
					'allow_null' => 0,
					'return_format' => 'value',
					'wrapper' => array(
						'width' => '33',
					),
				),
				array(
					'key' => 'field_5a711a6d98e6c',
					'label' => 'Compact Multi-Day End Date',
					'name' => 'date_format_compact_multi_end',
					'type' => 'select',
					'choices' => $date_formats,
					'default_value' => array(
						0 => 'M j, Y',
					),
					'allow_null' => 0,
					'return_format' => 'value',
					'wrapper' => array(
						'width' => '33',
					),
				),
				array(
					'key' => 'field_5a711add98e6d',
					'label' => 'Time Format',
					'name' => 'time_format',
					'type' => 'select',
					'choices' => array(
						'g:ia' => '1:21pm',
						'g:i a' => '1:21 pm',
						'g:iA' => '1:21PM',
						'H:i' => '13:21',
					),
					'default_value' => array(
						0 => 'g:ia',
					),
					'allow_null' => 0,
					'return_format' => 'value',
					'wrapper' => array(
						'width' => '25',
					),
				),
				array(
					'key' => 'field_timedatesep73847927483',
					'label' => 'Date/Time Separator',
					'name' => 'datetime_sep',
					'type' => 'text',
					'default_value' => ' – ',
					'wrapper' => array(
						'width' => '25',
					),
				),
				array(
					'key' => 'field_timedatesep2_729385610',
					'label' => 'Date/Time Separator 2',
					'name' => 'datetime_sep2',
					'type' => 'text',
					'default_value' => ', ',
					'wrapper' => array(
						'width' => '25',
					),
				),
				array(
					'key' => 'field_timedaterange733636483',
					'label' => 'Date/Time Range Character',
					'name' => 'datetime_range',
					'type' => 'text',
					'default_value' => '–',
					'wrapper' => array(
						'width' => '25',
					),
				),
			),

		),
		array(
			'key' => 'field_5a6e820093be4',
			'label' => 'Google Maps API Key',
			'name' => 'google_maps_api_key',
			'type' => 'text',
			'instructions' => '<a href="https://developers.google.com/maps/documentation/javascript/get-api-key"
			target="_blank">Get Your API Key Here</a>',
			'wrapper' => array(
				'width' => '50',
			),
		),
		array(
			'key' => 'field_5a711b7d7ee7b',
			'label' => 'Map Link',
			'name' => 'map_link',
			'type' => 'true_false',
			'message' => 'Display Map Link Buttons',
			'default_value' => 1,
			'wrapper' => array(
				'width' => '50',
			),
		),
		array(
			'key' => 'field_5a71494e83bcb',
			'label' => 'Show Map',
			'name' => 'show_map_on_detail_page',
			'type' => 'true_false',
			'message' => 'Show a Google map with pin on the individual event page',
			'default_value' => 0,
			'wrapper' => array(
				'width' => '50',
			),
		),
		array(
			'key' => 'field_5a8123e9241f6',
			'label' => 'Default Map Zoom Level',
			'name' => 'default_zoom_level',
			'type' => 'range',
			'instructions' => 'select how far zoomed in the maps appear by default',
			'default_value' => 15,
			'min' => 8,
			'max' => 21,
			'step' => 1,
			'prepend' => '-',
			'append' => '+',
			'wrapper' => array(
				'width' => '50',
			),
		),
		array(
			'key' => 'field_mapjson738474635',
			'label' => 'Google Maps JSON',
			'name' => 'google_maps_json',
			'type' => 'textarea',
			'instructions' => 'Generate JSON map stype code or edit existing code here: <a href="https://mapstyle.withgoogle.com/">https://mapstyle.withgoogle.com</a>',
		),
		array(
			'key' => 'field_5a711b987ee7c',
			'label' => 'Add to gCal',
			'name' => 'add_to_gcal',
			'type' => 'true_false',
			'message' => 'Display Add to Google Calendar Buttons',
			'default_value' => 1,
		),
		array(
			'key' => 'field_homecountry17593483',
			'label' => 'Home Country',
			'name' => 'home_country',
			'type' => 'text',
			'instructions' => 'If the majority of your events are in one country, enter
				your home country here to override some location displays. Hides the home
				country name in most places. Provides <strong>City, State/Province</strong>
				for the short version of your home country and <strong>City, Country</strong>
				short version display for others.',
			'default_value' => 'United States',
		),
		array(
			'key' => 'field_5a711c1103fad',
			'label' => 'Archive by Year',
			'name' => 'archive_by_year',
			'type' => 'true_false',
			'message' => 'Group Past Events by Year',
			'default_value' => 1,
			'wrapper' => array(
				'width' => '50',
			),
		),
		array(
			'key' => 'field_5a71e021fe462',
			'label' => 'Collapse/Expand',
			'name' => 'accordion',
			'type' => 'true_false',
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5a711c1103fad',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'message' => 'Collapse/Expand Animation for Event Archives by Year',
			'default_value' => 1,
			'wrapper' => array(
				'width' => '50',
			),
		),
		array(
			'key' => 'field_5a711c6203fae',
			'label' => 'More Link (Compact View)',
			'name' => 'more_link',
			'type' => 'link',
			'return_format' => 'array',
			'wrapper' => array(
				'width' => '50',
			),
		),
		array(
			'key' => 'field_5a7120c836833',
			'label' => 'Number of Upcoming',
			'name' => 'number_of_upcoming',
			'type' => 'number',
			'instructions' => 'How Many Upcoming Events to Show in Compact View',
			'default_value' => 3,
			'min' => 1,
			'max' => 99,
			'step' => 1,
			'wrapper' => array(
				'width' => '50',
			),
		),
		array(
			'key' => 'field_5a71218b78f41',
			'label' => 'Show Description',
			'name' => 'show_description',
			'type' => 'true_false',
			'message' => 'Show Short Description in Compact View',
			'default_value' => 1,
			'wrapper' => array(
				'width' => '50',
			),
		),
		array(
			'key' => 'field_5a716c3632b88',
			'label' => 'Show Title',
			'name' => 'show_title',
			'type' => 'true_false',
			'message' => 'Show Title Field in Compact View',
			'default_value' => 1,
			'wrapper' => array(
				'width' => '50',
			),
		),
		array(
			'key' => 'field_showimage834j20f',
			'label' => 'Show Image',
			'name' => 'event_show_image',
			'type' => 'true_false',
			'message' => 'Show Image in Compact View',
			'default_value' => 1,
			'wrapper' => array(
				'width' => '33',
			),
		),
		/*
		array(
			'key' => 'field_placeimage3749275',
			'label' => 'Image Placement',
			'name' => 'event_image_placement',
			'type' => 'select',
			'choices' => array(
				'top' => 'top',
				'left' => 'left',
				'right' => 'right',
				'bottom' => 'bottom',
			),
			'default_value' => 'bottom',
			'return_format' => 'value',
			'wrapper' => array(
				'width' => '33',
			),
		),
		*/
		array(
			'key' => 'field_imagesize8290348',
			'label' => 'Image Size',
			'name' => 'event_image_preview_size',
			'default_value' => 'thumbnail',
			'type' => 'text',
			// 'type' => 'select',  // @TODO - make this a select that automatically gets all the sizes, if that's possible (tricky to get sizes after theme load from a plugin)
			// 'choices' => get_image_sizes(),
			// 'return_format' => 'value',
			// 'allow_null' => 0,
			'wrapper' => array(
				'width' => '33',
			),
		),
		array(
			'key' => 'field_eventcat7283947892',
			'label' => 'Events Categories',
			'name' => 'enable_categories',
			'type' => 'true_false',
			'message' => 'Enable Events Categories System',
			'default_value' => 1,
		),
		array(
			'key' => 'field_5a712237b7a78',
			'label' => 'No Events Text',
			'name' => 'no_events_text',
			'type' => 'wysiwyg',
			'default_value' => '<h2>There are currently upcoming no events.</h2>
<p>Please join the email list and we will keep you posted when new events get added.</p>',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-event-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
